# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui_design/design.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox4Notes = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox4Notes.sizePolicy().hasHeightForWidth())
        self.groupBox4Notes.setSizePolicy(sizePolicy)
        self.groupBox4Notes.setObjectName("groupBox4Notes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox4Notes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.notesLineEdit = QtWidgets.QLineEdit(self.groupBox4Notes)
        self.notesLineEdit.setObjectName("notesLineEdit")
        self.verticalLayout_4.addWidget(self.notesLineEdit)
        self.verticalLayout.addWidget(self.groupBox4Notes)
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout.addWidget(self.line_1)
        self.groupBox_Calibration = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Calibration.sizePolicy().hasHeightForWidth())
        self.groupBox_Calibration.setSizePolicy(sizePolicy)
        self.groupBox_Calibration.setObjectName("groupBox_Calibration")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_Calibration)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widgetRefractiveIndexCalibrateBtn = QtWidgets.QWidget(self.groupBox_Calibration)
        self.widgetRefractiveIndexCalibrateBtn.setObjectName("widgetRefractiveIndexCalibrateBtn")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetRefractiveIndexCalibrateBtn)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetReractiveIndexInput = QtWidgets.QWidget(self.widgetRefractiveIndexCalibrateBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetReractiveIndexInput.sizePolicy().hasHeightForWidth())
        self.widgetReractiveIndexInput.setSizePolicy(sizePolicy)
        self.widgetReractiveIndexInput.setObjectName("widgetReractiveIndexInput")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetReractiveIndexInput)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelRefractiveIndexText = QtWidgets.QLabel(self.widgetReractiveIndexInput)
        self.labelRefractiveIndexText.setObjectName("labelRefractiveIndexText")
        self.horizontalLayout.addWidget(self.labelRefractiveIndexText)
        self.lineEditRefractiveIndex = QtWidgets.QLineEdit(self.widgetReractiveIndexInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRefractiveIndex.sizePolicy().hasHeightForWidth())
        self.lineEditRefractiveIndex.setSizePolicy(sizePolicy)
        self.lineEditRefractiveIndex.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEditRefractiveIndex.setText("")
        self.lineEditRefractiveIndex.setObjectName("lineEditRefractiveIndex")
        self.horizontalLayout.addWidget(self.lineEditRefractiveIndex)
        self.verticalLayout_2.addWidget(self.widgetReractiveIndexInput)
        self.pushButtonCalibrate_PDs = QtWidgets.QPushButton(self.widgetRefractiveIndexCalibrateBtn)
        self.pushButtonCalibrate_PDs.setObjectName("pushButtonCalibrate_PDs")
        self.verticalLayout_2.addWidget(self.pushButtonCalibrate_PDs)
        self.horizontalLayout_2.addWidget(self.widgetRefractiveIndexCalibrateBtn)
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(self.groupBox_Calibration)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.widgetCalibrationValues = QtWidgets.QWidget(self.groupBox_Calibration)
        self.widgetCalibrationValues.setObjectName("widgetCalibrationValues")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetCalibrationValues)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_cCAValue = QtWidgets.QLabel(self.widgetCalibrationValues)
        self.label_cCAValue.setObjectName("label_cCAValue")
        self.gridLayout.addWidget(self.label_cCAValue, 0, 2, 1, 1)
        self.label_cCA = QtWidgets.QLabel(self.widgetCalibrationValues)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cCA.sizePolicy().hasHeightForWidth())
        self.label_cCA.setSizePolicy(sizePolicy)
        self.label_cCA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cCA.setObjectName("label_cCA")
        self.gridLayout.addWidget(self.label_cCA, 0, 1, 1, 1)
        self.label_alpha = QtWidgets.QLabel(self.widgetCalibrationValues)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_alpha.sizePolicy().hasHeightForWidth())
        self.label_alpha.setSizePolicy(sizePolicy)
        self.label_alpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_alpha.setObjectName("label_alpha")
        self.gridLayout.addWidget(self.label_alpha, 2, 1, 1, 1)
        self.label_cOA = QtWidgets.QLabel(self.widgetCalibrationValues)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cOA.sizePolicy().hasHeightForWidth())
        self.label_cOA.setSizePolicy(sizePolicy)
        self.label_cOA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cOA.setObjectName("label_cOA")
        self.gridLayout.addWidget(self.label_cOA, 1, 1, 1, 1)
        self.label_progress = QtWidgets.QLabel(self.widgetCalibrationValues)
        self.label_progress.setEnabled(True)
        self.label_progress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_progress.setObjectName("label_progress")
        self.gridLayout.addWidget(self.label_progress, 0, 3, 1, 1)
        self.label_alpha_VALUE = QtWidgets.QLabel(self.widgetCalibrationValues)
        self.label_alpha_VALUE.setObjectName("label_alpha_VALUE")
        self.gridLayout.addWidget(self.label_alpha_VALUE, 2, 2, 1, 1)
        self.label_cOAValue = QtWidgets.QLabel(self.widgetCalibrationValues)
        self.label_cOAValue.setObjectName("label_cOAValue")
        self.gridLayout.addWidget(self.label_cOAValue, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.widgetCalibrationValues)
        self.verticalLayout.addWidget(self.groupBox_Calibration)
        self.groupBox_Aperture = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Aperture.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Aperture.sizePolicy().hasHeightForWidth())
        self.groupBox_Aperture.setSizePolicy(sizePolicy)
        self.groupBox_Aperture.setObjectName("groupBox_Aperture")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_Aperture)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_MeasureAperture = QtWidgets.QPushButton(self.groupBox_Aperture)
        self.pushButton_MeasureAperture.setObjectName("pushButton_MeasureAperture")
        self.horizontalLayout_4.addWidget(self.pushButton_MeasureAperture)
        self.labelApertureTransmittance = QtWidgets.QLabel(self.groupBox_Aperture)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelApertureTransmittance.sizePolicy().hasHeightForWidth())
        self.labelApertureTransmittance.setSizePolicy(sizePolicy)
        self.labelApertureTransmittance.setObjectName("labelApertureTransmittance")
        self.horizontalLayout_4.addWidget(self.labelApertureTransmittance)
        self.labelApertureTransmittanceValue = QtWidgets.QLabel(self.groupBox_Aperture)
        self.labelApertureTransmittanceValue.setObjectName("labelApertureTransmittanceValue")
        self.horizontalLayout_4.addWidget(self.labelApertureTransmittanceValue)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_Aperture)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.groupBox_Measurement = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Measurement.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Measurement.sizePolicy().hasHeightForWidth())
        self.groupBox_Measurement.setSizePolicy(sizePolicy)
        self.groupBox_Measurement.setObjectName("groupBox_Measurement")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_Measurement)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalWidgetStartMeasurementProgress = QtWidgets.QWidget(self.groupBox_Measurement)
        self.horizontalWidgetStartMeasurementProgress.setObjectName("horizontalWidgetStartMeasurementProgress")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidgetStartMeasurementProgress)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonStartStopMeasurement = QtWidgets.QPushButton(self.horizontalWidgetStartMeasurementProgress)
        self.pushButtonStartStopMeasurement.setObjectName("pushButtonStartStopMeasurement")
        self.horizontalLayout_5.addWidget(self.pushButtonStartStopMeasurement)
        self.progressBarMeasurement = QtWidgets.QProgressBar(self.horizontalWidgetStartMeasurementProgress)
        self.progressBarMeasurement.setProperty("value", 0)
        self.progressBarMeasurement.setObjectName("progressBarMeasurement")
        self.horizontalLayout_5.addWidget(self.progressBarMeasurement)
        self.verticalLayout_3.addWidget(self.horizontalWidgetStartMeasurementProgress)
        self.label_LiveViewMeasurement = QtWidgets.QLabel(self.groupBox_Measurement)
        self.label_LiveViewMeasurement.setObjectName("label_LiveViewMeasurement")
        self.verticalLayout_3.addWidget(self.label_LiveViewMeasurement)
        self.verticalLayout.addWidget(self.groupBox_Measurement)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayoutPdSignals = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPdSignals.setObjectName("horizontalLayoutPdSignals")
        self.groupBox_PD_Ref_Signal = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PD_Ref_Signal.setObjectName("groupBox_PD_Ref_Signal")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_PD_Ref_Signal)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_PD_Ref_Signal = QtWidgets.QLabel(self.groupBox_PD_Ref_Signal)
        self.label_PD_Ref_Signal.setObjectName("label_PD_Ref_Signal")
        self.horizontalLayout_7.addWidget(self.label_PD_Ref_Signal)
        self.horizontalLayoutPdSignals.addWidget(self.groupBox_PD_Ref_Signal)
        self.groupBox_PD_OA_Signal = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PD_OA_Signal.setObjectName("groupBox_PD_OA_Signal")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_PD_OA_Signal)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_PD_OA_Signal = QtWidgets.QLabel(self.groupBox_PD_OA_Signal)
        self.label_PD_OA_Signal.setObjectName("label_PD_OA_Signal")
        self.horizontalLayout_8.addWidget(self.label_PD_OA_Signal)
        self.horizontalLayoutPdSignals.addWidget(self.groupBox_PD_OA_Signal)
        self.groupBox_PD_CA_Signal = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PD_CA_Signal.setObjectName("groupBox_PD_CA_Signal")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_PD_CA_Signal)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_PD_CA_Signal = QtWidgets.QLabel(self.groupBox_PD_CA_Signal)
        self.label_PD_CA_Signal.setObjectName("label_PD_CA_Signal")
        self.horizontalLayout_9.addWidget(self.label_PD_CA_Signal)
        self.horizontalLayoutPdSignals.addWidget(self.groupBox_PD_CA_Signal)
        self.verticalLayout.addLayout(self.horizontalLayoutPdSignals)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "z-Scan Measurement Manager"))
        self.groupBox4Notes.setTitle(_translate("MainWindow", "Notes on this measurement: "))
        self.notesLineEdit.setText(_translate("MainWindow", "Type in a note here (e.g. sample material and concentration)!"))
        self.groupBox_Calibration.setTitle(_translate("MainWindow", "1. Calibration: Insert medium and open the aperture (S=1)"))
        self.labelRefractiveIndexText.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Refractive index</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">of sample (optional)</p></body></html>"))
        self.pushButtonCalibrate_PDs.setText(_translate("MainWindow", "Calibrate photodiodes"))
        self.label_cCAValue.setText(_translate("MainWindow", "pending"))
        self.label_cCA.setText(_translate("MainWindow", "c_CA ="))
        self.label_alpha.setText(_translate("MainWindow", "<html><head/><body><p>α / m<span style=\" vertical-align:super;\">-1</span> =</p></body></html>"))
        self.label_cOA.setText(_translate("MainWindow", "c_OA ="))
        self.label_progress.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">in Progress...</p></body></html>"))
        self.label_alpha_VALUE.setText(_translate("MainWindow", "pending"))
        self.label_cOAValue.setText(_translate("MainWindow", "pending"))
        self.groupBox_Aperture.setTitle(_translate("MainWindow", "2. Align aperture"))
        self.pushButton_MeasureAperture.setText(_translate("MainWindow", "Measure aperture transmission"))
        self.labelApertureTransmittance.setText(_translate("MainWindow", "S ="))
        self.labelApertureTransmittanceValue.setText(_translate("MainWindow", "pending"))
        self.groupBox_Measurement.setTitle(_translate("MainWindow", "3. Start measurement"))
        self.pushButtonStartStopMeasurement.setText(_translate("MainWindow", "Start measurement"))
        self.label_LiveViewMeasurement.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">A live view of the measured z-scan curve</p></body></html>"))
        self.groupBox_PD_Ref_Signal.setTitle(_translate("MainWindow", "PD_Ref Signal"))
        self.label_PD_Ref_Signal.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PD_Ref Signal</p></body></html>"))
        self.groupBox_PD_OA_Signal.setTitle(_translate("MainWindow", "PD_OA Signal"))
        self.label_PD_OA_Signal.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PD_OA Signal</p></body></html>"))
        self.groupBox_PD_CA_Signal.setTitle(_translate("MainWindow", "PD_CA Signal"))
        self.label_PD_CA_Signal.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">PD_CA Signal</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

